# Users with delete access can run this workflow to delete packages

name: DeletePackages

on: 
  workflow_dispatch:
      inputs:
        owner:
          description: 'Repo Owner'     
          required: true
          default: 'ballerina-platform'
        repo:
          description: 'Repository'     
          required: true
          default: 'ballerina-lang'
        package:
          description: 'Specific package(groupId.artifactId)'
          required: true
        version:
          description: 'Package version'
          required: true

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - name: Read access list
        run: "cat ./delete-packages-scripts/usernames_with_package_delete_access.json | jq -r '.usernames[]|select(.username==\"${{github.actor}}\").username' > /tmp/auth-user.json"
      - name: Set authorized username
        id: setUname
        run: printf "::set-output name=foundUname::%s" $(cat /tmp/auth-user.json)
      - name: Get package version ids
        if: steps.setUname.outputs.foundUname != ''
        run: |
          curl -H "Authorization: bearer ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/orgs/${{ github.event.inputs.owner }}/packages/maven/${{ github.event.inputs.package }}/versions?per_page=100 -o /tmp/version-ids.json
      - name: Filter packages and set version ID
        id: setid
        if: steps.setUname.outputs.foundUname != ''
        run: printf "::set-output name=versionId::%s" $(cat /tmp/version-ids.json | jq -r '.[] | select(.name=="${{ github.event.inputs.version }}")|.id')
      - name: Delete selected package
        if: steps.setUname.outputs.foundUname != '' && steps.setid.outputs.versionId != ''
        run: |
          curl -X DELETE -H "Authorization: bearer ${{ secrets.DELETE_PACKAGE_PAT }}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/orgs/${{ github.event.inputs.owner }}/packages/maven/${{ github.event.inputs.package }}/versions/${{ steps.setid.outputs.versionId }}
