name: Delete stdlibs in staging central

on:
  workflow_dispatch: 
    inputs:
      tag:
        description: Release tag
        required: true
        default: master

jobs:
  delete-from-staging-central:
    runs-on: ubuntu-latest
    env:
      STAGE_KEY: ${{secrets.STAGE_KEY}}
      STAGE_CERT: ${{secrets.STAGE_CERT}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get gradle.properties from the distribution
        uses: wei/wget@v1
        with:
          args: https://raw.githubusercontent.com/ballerina-platform/ballerina-distribution/${{github.event.inputs.tag}}/gradle.properties
             -P ./dependabot/resources
      - name: Create CSV to store module details
        run: touch ModuleDetails.csv
      - name: Execute Ballerina script
        uses: ballerina-platform/ballerina-action@2201.0.3
        with:
          args: run ./dependabot/delete_staging_central_stdlibs.bal
      - name: Delete stdlibs from staging central
        run: |
          echo "$STAGE_KEY" > bc-stage-admin-client.key ;
          echo "$STAGE_CERT" > bc-stage-admin-client.crt ;
          while IFS=, read -r level package version
          do
            curl -v -X DELETE --key bc-stage-admin-client.key --cert bc-stage-admin-client.crt \
             https://admin.staging-central.ballerina.io/2.0/admin/packages/ballerina/$package/$version\?force\=true ;
          done < ModuleDetails.csv
